version: "3.8"

#*************************************#
#------- Services (Containers) -------#
#*************************************#
services:
  mariadb:
    image: mariadb:42
    container_name: mariadb
    init: true
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
      networks:
        - inception
      volumes:
        - mariadb:/var/lib/mysql
      restart: always

  wordpress:
    image: wordpress:42
    container_name: wordpress
    init: true
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
      networks:
        - inception
      volumes:
        - wordpress:/var/www/html
      restart: always
      depends_on:
        - mariadb

  nginx:
    image: nginx:42
    container_name: nginx
    init: true
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME
        - CERTS_KEY
        - CERTS_CRT
      networks:
        - inception
      ports:
        - "443:443"
      volumes:
        - wordpress:/var/www/html
        - static:/usr/share/nginx/html
      restart: always
      depends_on:
        - mariadb
        - wordpress
        -  static

#*************************************#
#-------------- Volumes --------------#
#*************************************#
volumes:
  mariadb:
    name: mariadb
    external: true
  wordpress:
    name: wordpress
    external: true
  static:
    name: static
    external: true

#*************************************#
#-------------- Networks -------------#
#*************************************#
networks:
  inception:
    name: inception
    driver: bridge


#*************************************#
#--------------- BONUS ---------------#
#*************************************#
#
#
#
